1 table and waiter
smruti-banty/restru-manage pull request #2
Opened 2024-01-22 19:12 UTC by SaiPranab

added support for addTable, deleteTable, getAllTable, getTableById
&
addWaiter, deleteWaiter, getAllWaiters, getWaiterById
&
getWaiterAssignedToTable(tableId)
assignTableToWaiter(waiterId, tableId)

2024-01-23 10:54 UTC, smruti-banty requested changes
Change the file according to comment and test properly using postman

2024-01-23 10:54 UTC, smruti-banty commented on backend/src/main/java/com/lafista/backend/table/controller/RestaurantTableController.java
change url from `tables` to `table`

2024-01-23 10:54 UTC, smruti-banty commented on backend/src/main/java/com/lafista/backend/table/controller/RestaurantTableController.java
Use `DTO` class to handle request and response

2024-01-23 10:54 UTC, smruti-banty commented on backend/src/main/java/com/lafista/backend/table/controller/RestaurantTableController.java
Add method for `getByTableId` and update table name

2024-01-23 10:54 UTC, smruti-banty commented on backend/src/main/java/com/lafista/backend/waiter/controller/WaiterController.java
Remove response OK

2024-01-23 10:54 UTC, smruti-banty commented on backend/src/main/resources/application.properties
Remove below properties 

```server.port=1205
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

2024-01-23 13:26 UTC, SaiPranab commented
- [ x ] remove response OK
- [ x ] add method for updateTable and getTableById
- [ x ] add method for updateWaiter and getWaiterById
- [ x ] add DTO classes for handling requests
- [ x ] change urls tables to table 
- [ x ] change urls waiters to waiter

2024-01-23 15:04 UTC, smruti-banty approved these changes
LGTM.

2024-01-24 08:39 UTC, smruti-banty approved these changes

2024-01-24 08:39 UTC, merged